tweeter/config/routes.rb
Rails.application.routes.draw do
root "posts#index"
resources :posts do
    collection do
      post :confirm
    end
end
resources :posts
end

tweeter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tweeter/app/models/post.rb
class Post < ApplicationRecord
    validates  :content, length: {in: 1..140} , presence: true
end

tweeter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tweeter/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts= Post.all
    end

    def new
        @post= Post.new
    end

    def show 
        @post = Post.find(params[:id])
    end

    def confirm
        @post = Post.new(posts_params)
    end

    def edit
       @post=Post.find(params[:id])
    end


    def create
        @post=Post.new(posts_params)
     
        if @post.save
        redirect_to posts_path, notice: "J'ai éffectué un tweet ♣"
        else
           render :new
        end
    end

    def update
        @post=Post.find(params[:id])
        if @post.update(posts_params)
           redirect_to posts_path, notice: "J'ai Modifié le tweet ♣"
        else
           render :new
        end
    end


    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path, notice: "J'ai Supprimé le tweet !!!"
    end


    private
 def posts_params
   params.require(:post).permit(:nom, :content, :title)
 end
end

tweeter/app/helpers/application_helper.rb
module ApplicationHelper
end

tweeter/app/helpers/home_helper.rb
module HomeHelper
end

tweeter/app/helpers/posts_helper.rb
module PostsHelper
end

tweeter/app/helpers/tweets_helper.rb
module TweetsHelper
end

tweeter/app/views/posts/confirm.html.erb
<h3>Confirmez votre tweet</h3>
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p><%= @post.content %></p>
  <%= form.submit  "Confirmez" %>
<% end %>
<%= link_to 'Retour', :back %>

tweeter/app/views/posts/edit.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <!--Header-->
        <header id="header" class="skel-layers-fixed">
            <h1><a href="#">Twitter</a></h1>
            <nav id="nav">
                <ul>
                    <li><a href="#">Acceuil</a></li>
                    <li><a href="#">A Propos</a></li>
                    <li><a href="#">Contactez-Nous</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#" class="button special">Sign Up</a></li>
                </ul>
            </nav>
        </header>

        <!-- Banner -->
        <section id="banner">
            <div class="inner">
                <h2>This is Tweeter</h2>
                <p>Tweeter Application Web</p>
                <ul class="actions">
                <%= form_with model: @post, local:true do |form| %>
                    <% if @post.errors.any? %>
                      <h3 style="color:red;"> Une erreur est survenue </h3>
                      <ul>
                      <% @post.errors.full_messages.each do |msg| %>
                          <li style="color:red;"> <%= msg %> </li>
                       <% end %>
                       <br/><br/>
                      </ul>
                    <% end %>
                    <li>
                      <%= form.label :content %>
                      <%= form.text_area :content %>
                    </li><br/><br/>
                    <li>
                      <%= form.submit "Modifier le post"%>
                    </li>
                   <% end %>
                    
                </ul>
            </div>
        </section>


        <!-- Footer -->
        <footer id="footer">
            <div class="container">
                <ul class="copyright">
                    <li>&copy; Chabla. All rights reserved.</li>
                    <li>Design: <a href="http://templated.co">ChablaDESIGN</a></li>
                    <li>Images: <a href="http://unsplash.com">ChablaIMAGE</a></li>
                </ul>
            </div>
        </footer>

    </div>
</body>

</html>

tweeter/app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <!--Header-->
        <header id="header" class="skel-layers-fixed">
            <h1><a href="#">Twitter</a></h1>
            <nav id="nav">
                <ul>
                    <li><a href="#">Acceuil</a></li>
                    <li><a href="#">A Propos</a></li>
                    <li><a href="#">Contactez-Nous</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#" class="button special">Sign Up</a></li>
                </ul>
            </nav>
        </header>

        <!-- Banner -->
        <section id="banner">
            <div class="inner">
                <p>La liste des tweets</p>
                <p style="color:green;"><%= notice %></p>
                <div> <%= link_to "Faites un nouveau tweet", new_post_path() %></div>
                <br/><br/>
                <% @posts.each do |post| %>
                <div style="border: 1px black solid; box-shadow: 6px 6px 6px blue;"> <%= post.content %> <span style="margin-left:10px"> <%= link_to "Voir le tweet", post_path(post) %> </span>  <span style="margin-left:10px"><%= link_to "Modifier le tweet", edit_post_path(post) %></span>  <span style="margin-left:10px"><%= link_to "Supprimer le tweet", post_path(post), method: :delete, data: { confirm: 'Voulez-vous vraiment supprimer cet tweet' }%></span> </div>
                <br/>
                <% end %>

            </div>
        </section>


        <!-- Footer -->
        <footer id="footer">
            <div class="container">
                <ul class="copyright">
                    <li>&copy; Chabla. All rights reserved.</li>
                    <li>Design: <a href="http://templated.co">ChablaDESIGN</a></li>
                    <li>Images: <a href="http://unsplash.com">ChablaIMAGE</a></li>
                </ul>
            </div>
        </footer>

    </div>
</body>

</html>

tweeter/app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <!--Header-->
        <header id="header" class="skel-layers-fixed">
            <h1><a href="#">Twitter</a></h1>
            <nav id="nav">
                <ul>
                    <li><a href="#">Acceuil</a></li>
                    <li><a href="#">A Propos</a></li>
                    <li><a href="#">Contactez-Nous</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#" class="button special">Sign Up</a></li>
                </ul>
            </nav>
        </header>

        <!-- Banner -->
        <section id="banner">
            <div class="inner">
                <h2>This is Tweeter</h2>
                <p>Tweeter Application Web</p>
                <ul class="actions">
                <%= form_with(model: @post, local: true ,url: confirm_posts_path ) do |form| %>
                    <% if @post.errors.any? %>
                        <div id="error_explanation">
                        <h3 style="color:red;"><%= @post.errors.count %>Il y a des erreurs.</h3>
                        <ul>
                        <% @post.errors.full_messages.each do |msg| %>
                            <li style="color:red;"><%= msg %></li>
                        <% end %>
                        </ul>
                        </div>
                    <% end %>
                    <li>
                      <%= form.label :content %>
                      <%= form.text_area :content %>
                    </li><br/><br/>
                    <li>
                      <%= form.submit "Publier le post"%>
                    </li>
                   <% end %>
                    
                </ul>
            </div>
        </section>


        <!-- Footer -->
        <footer id="footer">
            <div class="container">
                <ul class="copyright">
                    <li>&copy; Chabla. All rights reserved.</li>
                    <li>Design: <a href="http://templated.co">ChablaDESIGN</a></li>
                    <li>Images: <a href="http://unsplash.com">ChablaIMAGE</a></li>
                </ul>
            </div>
        </footer>

    </div>
</body>

</html>

tweeter/app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <!--Header-->
        <header id="header" class="skel-layers-fixed">
            <h1><a href="#">Twitter</a></h1>
            <nav id="nav">
                <ul>
                    <li><a href="#">Acceuil</a></li>
                    <li><a href="#">A Propos</a></li>
                    <li><a href="#">Contactez-Nous</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#" class="button special">Sign Up</a></li>
                </ul>
            </nav>
        </header>

        <!-- Banner -->
        <section id="banner">
            <div class="inner">
                <div style="border: 1px black solid; box-shadow: 6px 6px 6px blue;"> <%= @post.content %></div>
                <br/>
                <div> <%= link_to "retournez aux tweets", posts_path() %></div>
                <hr/>
            </div>
        </section>


        <!-- Footer -->
        <footer id="footer">
            <div class="container">
                <ul class="copyright">
                    <li>&copy; Chabla. All rights reserved.</li>
                    <li>Design: <a href="http://templated.co">ChablaDESIGN</a></li>
                    <li>Images: <a href="http://unsplash.com">ChablaIMAGE</a></li>
                </ul>
            </div>
        </footer>

    </div>
</body>

</html>